### ISSUE TITLE
Look into why graphql.planetary.pub has stopped syncing

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/planetary-graphql#35]
The pubs data is out of date, indicating it isnt syncing properly

**Comment by rabble** [comment]
@mixmix can you give an update on this?

**Comment by mixmix** [comment]
Sorry I didn't get to this. Have been waiting for the new system pattern to settle before debugging.
I assume graphql.planetary.pub is gonna be wound down as we move to a more room-centric model with many smaller graphql servers?

Let's watch how they behave

**Comment by mplorentz** [comment]
It seems like they are behaving. Closing.
